[package]
name = "hot"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
crossterm = { version = "0.25.0", default-features = false }
mio = { version = "0.8.4", default-features = false, features = ["os-ext", "os-poll"] }
